Sprint 1
ClevertecFrontendLab/VikaOnoshko pull request #1
Opened 2024-02-13 06:18 UTC by VikaOnoshko

2024-02-13 06:20 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 3.
Количество непройденных тестов: 0.
***
**1440-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/VikaOnoshko/1707805232/1440-1.png)
***
**1440-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/VikaOnoshko/1707805232/1440-2.png)
***
**1440-3.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/VikaOnoshko/1707805232/1440-3.png)
***
**360-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/VikaOnoshko/1707805232/360-1.png)
***
**360-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/VikaOnoshko/1707805232/360-2.png)
***
**360-3.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/VikaOnoshko/1707805232/360-3.png)
***
**834-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/VikaOnoshko/1707805232/834-1.png)
***
**834-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/VikaOnoshko/1707805232/834-2.png)
***
**834-3.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/VikaOnoshko/1707805232/834-3.png)

2024-02-13 06:51 UTC, Xaky0105 requested changes
Перепутан логотип на свернутом/развернутом сайдбаре
Также нужно поправить кнопку "Выход"
![image](https://github.com/ClevertecFrontendLab/VikaOnoshko/assets/81919274/c8e5c0b0-5707-497f-91c1-1eff6f81dd95)

Блок "Скачать приложение" уезжает на контейнер, а должен находиться внутри
![image](https://github.com/ClevertecFrontendLab/VikaOnoshko/assets/81919274/edd87f89-7313-4a0e-88af-4c3685ea660c)

На разрешении 360 нету отступа между блоками
![image](https://github.com/ClevertecFrontendLab/VikaOnoshko/assets/81919274/071172ef-e6d5-46f6-ac88-da4085c22dde)

Иконка календаря сверху должна быть немножко закрашена
![image](https://github.com/ClevertecFrontendLab/VikaOnoshko/assets/81919274/2d32b182-6a62-421e-aff7-89f1d816f8b1)

2024-02-13 06:51 UTC, Xaky0105 commented on src/components/main-page/main-page-card/main-page-card.tsx
> +    return (
в таких случаях можно не писать return

2024-02-14 06:29 UTC, Xaky0105 approved these changes

2024-02-14 08:04 UTC, merged